### ISSUE TITLE
Remove duplicate propertyURI in v0.1.0 Profiles

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_sample_profiles#45]
On the current master branch of the Sinopia Linked Data Editor, resource templates like `sinopia:resourceTemplate:bf2:Monograph:Instance` are not able to load because of repeated property templates resulting in this error when trying to load:
<img width="1333" alt="Screen Shot 2019-07-18 at 10 05 04 AM" src="https://user-images.githubusercontent.com/71847/61473379-89202900-a943-11e9-99ad-963e0bbae666.png">

Should run through remove or select unique property URIs for property templates.

**Comment by michelleif** [comment]
@jermnelson do not fix the ones in there now. we are getting new ones from LC.

**Comment by jermnelson** [comment]
See above; closing
